env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - env:
    - CGO_ENABLED=0
    ldflags:
    - -s -w -X github.com/ProtocolONE/rain/torrent.Version={{.Version}}
    goos:
    - linux
    - darwin
    - windows
    goarch:
    - amd64
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
